name: cldet24env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - pandas
  - scikit-image
  - tqdm
  - hydra-core
  - ultralytics
  - monai
  - segmentation-models-pytorch
  - timm  # pytorch-image-models
